# Generated by Django 3.0.3 on 2020-07-08 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('personal_email', models.EmailField(blank=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('subscribe_date', models.DateField(default=datetime.datetime.now)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
