# Generated by Django 3.0.3 on 2020-07-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
